import { Fingerprint, Headset, PenTool, Zap, Users, Briefcase, LayoutGrid } from 'lucide-react';

export const services = [
  {
    id: 1,
    slug: "brand-strategy",
    title: "Brand Strategy & Identity",
    subheading: "Build a Brand Guests Remember",
    description: "We define your market positioning through audience research, competitive analysis, guest behavior insights, and data-led objectives. From visual identity to brand messaging, we create a clear and consistent brand foundation across every touchpoint.",
    longDescription: "A brand is the emotional connection between your business and your guests. We help ambitious hotels, resorts, and restaurants discover their unique voice, design stunning visual identities, and position themselves strategically in crowded markets. We create brands that are not just seen, but remembered, trusted, and booked.",
    icon: Fingerprint,
    features: [
      "Brand positioning",
      "Visual identity system",
      "Moodboard design",
      "Typography and color palette",
      "Messaging framework",
      "Campaign concept direction"
    ],
    benefits: [
      "Stand out in highly competitive hospitality markets",
      "Command premium pricing and higher RevPAR",
      "Build deep trust and emotional connection with guests",
      "Ensure absolute consistency across all touchpoints"
    ],
    faqs: [
          {
                "question": "What is hospitality brand strategy?",
                "answer": "Hospitality brand strategy defines how a hotel or resort communicates its unique value, aesthetic, and guest experience to stand out in a competitive market."
          },
          {
                "question": "How does brand identity increase direct bookings?",
                "answer": "A strong brand identity builds immediate trust and emotional connection. When guests trust a brand's direct channel, they are less likely to book through third-party OTAs, increasing your revenue."
          }
    ],
    relatedArticles: [
          {
                "title": "The Anatomy of a Luxury Hotel Brand",
                "slug": "luxury-hotel-brand-anatomy"
          }
    ]
  },
  {
    id: 2,
    slug: "revenue-management",
    title: "Revenue Management",
    subheading: "Revenue Strategies That Increase Profitability",
    description: "We help hospitality brands optimize revenue through strategic pricing, OTA management, yield management, distribution optimization, competitor analysis, and revenue-focused campaign planning.",
    longDescription: "Stop leaving money on the table. Our revenue management experts analyze market trends, competitor pricing, and historical data to implement dynamic pricing strategies. We optimize your distribution channels to ensure you sell the right room, to the right guest, at the exact right time and price.",
    icon: Headset,
    features: [
      "OTA management",
      "Dynamic pricing support",
      "Yield management",
      "Distribution optimization",
      "Competitor analysis",
      "TRevPAR-focused strategy",
      "Revenue growth planning"
    ],
    benefits: [
      "Maximize overall property revenue and profitability",
      "Increase direct bookings to reduce OTA commissions",
      "Optimize pricing during both peak and off-peak seasons",
      "Make data-driven decisions rather than guessing"
    ],
    faqs: [
          {
                "question": "What is TRevPAR in hotel revenue management?",
                "answer": "Total Revenue Per Available Room (TRevPAR) calculates all revenue generated by a hotel (including food, beverage, and spa), providing a holistic view of profitability."
          },
          {
                "question": "How can dynamic pricing help my resort?",
                "answer": "Dynamic pricing algorithms adjust room rates in real-time based on market demand, competitor pricing, and historical booking velocity, ensuring maximum yield."
          }
    ],
    relatedArticles: [
          {
                "title": "How to Increase Direct Bookings by 30%",
                "slug": "increase-direct-bookings"
          }
    ]
  },
  {
    id: 3,
    slug: "website-design-seo",
    title: "Website Design, SEO & GEO AI",
    subheading: "Hotel Websites & AI-Ready Search Optimization",
    description: "Your website is your owned booking channel. We design seamless, mobile-first websites with strong user experience, Generative Engine Optimization (GEO), AI-ready structured data, local & technical SEO, and conversion-focused layouts that drive direct bookings.",
    longDescription: "Your website is your most profitable digital storefront. We design and develop lightning-fast, beautifully interactive websites optimized for conversions. Combined with our technical SEO and Generative Engine Optimization (GEO) expertise, we ensure your property ranks highly on Google and gets recommended across AI search engines like ChatGPT, Gemini, and Perplexity.",
    icon: PenTool,
    features: [
      "Hotel website design",
      "Mobile-first architecture",
      "Booking engine integration",
      "Generative Engine Optimization (GEO)",
      "AI Search positioning (ChatGPT & Gemini)",
      "Technical & Local SEO",
      "AI-ready Schema & structured data",
      "Conversion-focused page structure"
    ],
    benefits: [
      "Deliver a seamless, premium experience to your guests",
      "Gain top recommendation positioning across AI-powered searches",
      "Increase direct conversion rates with data-backed UX",
      "Attract high-intent search traffic from Google & AI engines"
    ],
    faqs: [
          {
                "question": "What is GEO (Generative Engine Optimization) for hotels?",
                "answer": "GEO optimizes your hotel's website content, entity authority, and schema markup so AI engines (such as ChatGPT, Gemini, and Perplexity) recommend your property when users search for luxury stays and travel options."
          },
          {
                "question": "Why is a custom hotel website better than a template?",
                "answer": "Custom hotel websites are engineered for conversion optimization, fast load speeds, technical SEO, and AI search readiness, directly funneling users into your booking engine without friction."
          }
    ],
    relatedArticles: [
          {
                "title": "Technical SEO & GEO Checklist for Hotels",
                "slug": "hotel-seo-checklist"
          }
    ]
  },
  {
    id: 4,
    slug: "performance-marketing",
    title: "Performance Marketing",
    subheading: "Performance Marketing Focused on ROI",
    description: "We execute highly targeted paid campaigns designed to capture demand, retarget interested audiences, and convert digital attention into bookings. Our campaigns focus on improving ROAS while lowering CPA.",
    longDescription: "Stop guessing with your ad spend. Our performance marketing methodology relies on strict ROI tracking and relentless optimization. We deploy highly targeted campaigns across Google Ads and Meta to ensure every advertising dollar translates into scalable revenue for your property.",
    icon: Zap,
    features: [
      "Meta Ads",
      "Google Ads",
      "Retargeting campaigns",
      "Lead generation campaigns",
      "Conversion-focused advertising",
      "Peak-season demand campaigns",
      "Budget allocation strategy",
      "ROAS and CPA tracking"
    ],
    benefits: [
      "Immediate visibility and direct booking generation",
      "Highly predictable and scalable guest acquisition",
      "Precise targeting of your ideal guest persona",
      "Continuous optimization for the lowest possible CPA"
    ],
    faqs: [
          {
                "question": "Which paid channels work best for luxury hotels?",
                "answer": "Google Ads (Search and Hotel Ads) capture high-intent travelers, while Meta Ads (Instagram and Facebook) excel at demand generation and retargeting past guests."
          },
          {
                "question": "How do you lower CPA in hospitality marketing?",
                "answer": "We lower Cost Per Acquisition (CPA) by refining audience targeting, improving ad creative, and ensuring landing pages have a high conversion rate."
          }
    ],
    relatedArticles: [
          {
                "title": "Lowering CPA with Meta Ads",
                "slug": "meta-ads-cpa-guide"
          }
    ]
  },
  {
    id: 5,
    slug: "seo-gmb",
    title: "GEO & GMB",
    subheading: "Control the First Trust Touchpoint",
    description: "Before guests visit your website, they often discover you on Google. We optimize your Google Business Profile to improve local visibility, strengthen trust, manage reviews, upload high-quality assets, and drive users toward direct booking links.",
    longDescription: "Local visibility is everything in hospitality. We hyper-optimize your Google Business Profile (GMB) and execute targeted local SEO strategies to ensure you own the 'near me' searches. From review management to authoritative local citations, we put your property on the map.",
    icon: Users,
    features: [
      "GEO & GMB",
      "Review management",
      "High-fidelity asset uploads",
      "Local SEO improvement",
      "Direct booking link integration",
      "Map pack visibility strategy"
    ],
    benefits: [
      "Dominate local Google Maps search results",
      "Drive massive increases in phone calls and directions",
      "Build trust through active review management",
      "Capture high-intent local searchers instantly"
    ],
    faqs: [
          {
                "question": "Why is Google Business Profile important for hotels?",
                "answer": "Google Business Profile dictates your visibility in the Google Local Pack and Maps. It is often the first touchpoint where potential guests see reviews, photos, and direct booking links."
          },
          {
                "question": "How do we improve our local SEO ranking?",
                "answer": "Local SEO is improved by generating consistent NAP (Name, Address, Phone) citations, actively responding to reviews, and uploading high-fidelity visual assets regularly."
          }
    ],
    relatedArticles: [
          {
                "title": "Dominating the Google Local Pack",
                "slug": "google-local-pack-guide"
          }
    ]
  },
  {
    id: 6,
    slug: "content-copywriting",
    title: "Content Creation & Copywriting",
    subheading: "Visual Storytelling That Reflects Luxury",
    description: "Hospitality is experienced through visuals before it is experienced in person. We create hotel photography, video content, promotional shoots, reels, menus, tours, and brand stories that capture comfort, ambience, service, and experience.",
    longDescription: "Content is the voice of your brand. Our expert writers produce high-value, evocative copy that transports guests to your property before they even book. From website copy that sells the experience to engaging blogs and newsletters, we write words that work.",
    icon: Briefcase,
    features: [
      "Hotel photography",
      "Video production",
      "Reels and short-form content",
      "Promotional shoots",
      "Storytelling concepts",
      "Menu and experience content",
      "Hospitality-focused copywriting"
    ],
    benefits: [
      "Create an emotional connection with potential guests",
      "Persuade visitors to book direct with confidence",
      "Provide massive value that builds immediate trust",
      "Feed your SEO strategy with high-quality text"
    ],
    faqs: [
          {
                "question": "What makes good hospitality copywriting?",
                "answer": "Good hospitality copywriting is evocative, descriptive, and emotionally engaging. It sells the experience and comfort of the property rather than just the physical amenities."
          },
          {
                "question": "Do we need professional hotel photography?",
                "answer": "Yes. High-quality visual assets are the single most important conversion factor for hotels. Poor photography directly reduces perceived value and lowers Average Daily Rate (ADR)."
          }
    ],
    relatedArticles: [
          {
                "title": "Writing Hotel Copy That Converts",
                "slug": "hotel-copywriting-tips"
          }
    ]
  },
  {
    id: 7,
    slug: "influencer-pr",
    title: "Influencer & PR Outreach",
    subheading: "Amplify Reach Through Meaningful Collaborations",
    description: "We collaborate with relevant travel creators, lifestyle influencers, and hospitality voices to build authentic brand awareness, trust, and audience engagement. From campaign planning to influencer coordination and content execution, we help brands create meaningful connections that drive visibility and conversions.",
    longDescription: "Word of mouth is digital now. We connect your brand with highly vetted travel influencers, food bloggers, and digital publications. Our strategic outreach generates authentic buzz, stunning user-generated content, and authoritative backlinks that elevate your brand's prestige.",
    icon: Users,
    features: [
      "Influencer campaign planning",
      "Creator shortlisting",
      "Collaboration coordination",
      "Content execution",
      "PR outreach",
      "Audience engagement strategy",
      "Trust-building campaigns"
    ],
    benefits: [
      "Tap into established, highly engaged audiences",
      "Generate stunning, authentic user-generated content",
      "Gain high-authority backlinks for SEO",
      "Elevate brand prestige and social proof"
    ],
    faqs: [
          {
                "question": "How do you measure ROI from travel influencers?",
                "answer": "We measure influencer ROI through trackable affiliate links, dedicated promo codes, direct traffic spikes during campaigns, and the reuse value of the User-Generated Content (UGC) provided."
          },
          {
                "question": "What is the difference between PR and Influencer Marketing?",
                "answer": "PR secures authority features in digital publications and travel magazines for brand prestige, while Influencer Marketing taps into creator audiences for authentic social proof and visual content."
          }
    ],
    relatedArticles: [
          {
                "title": "Vetting Travel Influencers in 2024",
                "slug": "vetting-travel-influencers"
          }
    ]
  },
  {
    id: 8,
    slug: "social-media-management",
    title: "Social Media Management",
    subheading: "Social Media That Builds Brand Presence",
    description: "We elevate visual storytelling and community engagement to transform passive scrollers into engaged audiences and confirmed guests. Our social media strategies are designed for hospitality brands that want stronger visibility, better engagement, and premium brand perception.",
    longDescription: "Hospitality is visual, and social media is your digital lookbook. We craft data-driven social strategies that stop the scroll, spark wanderlust, and drive bookings across Instagram, Facebook, and TikTok. We handle everything from content creation to daily community engagement.",
    icon: LayoutGrid,
    features: [
      "Instagram feed planning",
      "Reels and story concepts",
      "Monthly content calendars",
      "Creative design",
      "Caption and copywriting",
      "Audience engagement",
      "Campaign-led posting"
    ],
    benefits: [
      "Showcase your property's unique aesthetic daily",
      "Rapidly expand your reach and brand awareness",
      "Drive highly engaged traffic to your booking engine",
      "Build a loyal, vocal community of brand advocates"
    ],
    faqs: [
          {
                "question": "How often should a hotel post on Instagram?",
                "answer": "Hotels should aim for 3 to 5 high-quality posts per week, supplemented by daily Stories to showcase behind-the-scenes operations, guest experiences, and real-time events."
          },
          {
                "question": "Does social media actually drive direct bookings?",
                "answer": "Yes. A highly visual, engaged social media presence builds wanderlust and brand recall, often serving as the discovery platform before a user navigates to your booking engine."
          }
    ],
    relatedArticles: [
          {
                "title": "Instagram Strategies for Resorts",
                "slug": "instagram-resort-strategy"
          }
    ]
  }
];
